<#
.SYNOPSIS
    Adds the KFS Claude Code guardrails to a Rock clone.

.DESCRIPTION
    Layers two sources into a Rock clone:

        Rock v20 guardrails   <Rock20>\CLAUDE.md and .claude\rules   (linked, never copied)
        KFS curated delta     <Guardrails>\                          (this folder)

    It never writes over, moves or deletes a file the clone tracks. Everything it creates is
    Claude Code's own per-machine configuration, listed in the clone's .git\info\exclude:

        CLAUDE.local.md               imports Rock20's CLAUDE.md, then CLAUDE-kfs.md
        .claude\rules\rock\           junction to Rock20's rules
        .claude\rules\kfs\            junction to the KFS rules
        .claude\settings.local.json   KFS permissions and hooks, merged into what is there

    Rock's guardrails come from Rock20 whatever version the clone targets:

        v17, v18   Rock ships none. Both layers are added.
        v19        Rock ships an early CLAUDE.md of its own. It is left in place and skipped
                   through claudeMdExcludes, so only Rock20's loads.
        Rock20     Rock's guardrails are already local. Only the KFS layer is added.

    A clone that ships its own .claude\rules but is not -Rock20 is refused: loading both would
    give Claude two versions of Rock's rules.

    Also creates machine-wide skill junctions in ~\.claude\skills\ so skills are available in
    every clone without per-repo wiring.

    Idempotent. Re-run after changing sources or adding skills. A clone set up by an earlier
    version of this script is migrated: its generated CLAUDE.md and its commands and hooks
    junctions are removed, and its copied settings.json is merged into settings.local.json.

.EXAMPLE
    .\setup.ps1 -Target C:\KFSRepo\Rock\Rock17

.EXAMPLE
    .\setup.ps1 -Target C:\KFSRepo\Rock\Rock18 `
                -Rock20 C:\KFSRepo\Rock\Rock20 `
                -Guardrails C:\KFSRepo\Rock\KFSRockAssemblies-guardrails\.guardrails
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string] $Target,

    [string] $Rock20 = 'C:\KFSRepo\Rock\Rock20',

    [string] $Guardrails,

    [switch] $SkipSkills
)

$ErrorActionPreference = 'Stop'

# $PSScriptRoot is not reliably populated as a parameter default, so resolve it here.
if ([string]::IsNullOrWhiteSpace($Guardrails)) {
    $Guardrails = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$GeneratedHeader  = '<!-- GENERATED by .guardrails\setup.ps1 - do not edit, do not commit. -->'
# Also matches files generated before the folder was renamed from guardrails\ to .guardrails\.
$GeneratedPattern = 'GENERATED by \.?guardrails\\setup\.ps1'

function Fail($message) {
    Write-Host ''
    Write-Host "SETUP FAILED: $message" -ForegroundColor Red
    Write-Host ''
    Write-Host 'Nothing was changed. Fix the above and re-run.' -ForegroundColor Yellow
    exit 1
}

function Confirm-Source($path, $what) {
    if (-not (Test-Path -LiteralPath $path)) {
        Fail "$what not found: $path"
    }
}

function Test-Junction($path) {
    $item = Get-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
    return [bool]($item -and ($item.Attributes -band [IO.FileAttributes]::ReparsePoint))
}

# True when the clone's own repository tracks the path, or anything under it.
function Test-Tracked($relativePath) {
    $ErrorActionPreference = 'Continue'
    $tracked = & git -C $Target ls-files $relativePath 2>$null
    if ($LASTEXITCODE -ne 0) {
        Fail "Could not ask git what $Target tracks. The target must be a git clone."
    }
    return [bool]$tracked
}

function Get-GuardrailsCheckout {
    $ErrorActionPreference = 'Continue'
    $branch = & git -C $Guardrails rev-parse --abbrev-ref HEAD 2>$null
    $commit = & git -C $Guardrails log -1 --format='%h %s' 2>$null
    if ($branch) {
        return "'$branch' -> $commit"
    }
}

# Deletes the junction itself. It never recurses, so the folder it points at is untouched.
function Remove-Junction($path) {
    [IO.Directory]::Delete($path, $false)
}

# Preflight has already refused anything at $linkPath that is not a junction.
function Set-Junction($linkPath, $targetPath) {
    if (Test-Path -LiteralPath $linkPath) {
        Remove-Junction $linkPath
    }
    New-Item -ItemType Junction -Path $linkPath -Target $targetPath | Out-Null
    Write-Host ("  link  {0,-34} -> {1}" -f (Split-Path $linkPath -Leaf), $targetPath)
}

# No byte-order mark: Claude Code parses settings.local.json as plain JSON.
function Write-Utf8($path, $text) {
    [IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding($false)))
}

function Add-GitExclude($pattern) {
    $excludeFile = Join-Path $Target '.git\info\exclude'
    if (-not (Test-Path -LiteralPath $excludeFile)) { return }
    $lines = @(Get-Content -LiteralPath $excludeFile -ErrorAction SilentlyContinue)
    if ($lines -notcontains $pattern) {
        Add-Content -LiteralPath $excludeFile -Value $pattern
        Write-Host "  git   excluded $pattern"
    }
}

# --- Settings merging -------------------------------------------------------

function Read-Json($path) {
    $raw = Get-Content -LiteralPath $path -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return New-Object PSObject
    }
    try {
        return ConvertFrom-Json $raw
    }
    catch {
        Fail "$path is not valid JSON: $($_.Exception.Message)"
    }
}

function Set-Property($object, $name, $value) {
    if ($object.PSObject.Properties[$name]) {
        $object.$name = $value
    }
    else {
        $object | Add-Member -NotePropertyName $name -NotePropertyValue $value
    }
}

# Appends each item that $object.$name lacks, keeping the existing order.
function Add-ListItems($object, $name, $items) {
    $list = New-Object System.Collections.Generic.List[object]
    if ($object.PSObject.Properties[$name]) {
        foreach ($item in @($object.$name)) {
            if ($null -ne $item) { $list.Add($item) }
        }
    }
    foreach ($item in @($items)) {
        if ($null -ne $item -and -not $list.Contains($item)) { $list.Add($item) }
    }
    Set-Property $object $name $list.ToArray()
}

# Appends each hook entry whose command $object.$name does not already run.
function Add-HookEntries($object, $name, $entries) {
    $list = New-Object System.Collections.Generic.List[object]
    $commands = New-Object System.Collections.Generic.List[string]
    if ($object.PSObject.Properties[$name]) {
        foreach ($entry in @($object.$name)) {
            if ($null -eq $entry) { continue }
            $list.Add($entry)
            foreach ($hook in @($entry.hooks)) {
                if ($hook) { $commands.Add([string]$hook.command) }
            }
        }
    }
    foreach ($entry in @($entries)) {
        if ($null -eq $entry) { continue }
        $entryCommands = @(@($entry.hooks) | Where-Object { $_ } | ForEach-Object { [string]$_.command })
        $isNew = @($entryCommands | Where-Object { -not $commands.Contains($_) }).Count -gt 0
        if ($isNew) {
            $list.Add($entry)
            foreach ($command in $entryCommands) { $commands.Add($command) }
        }
    }
    Set-Property $object $name $list.ToArray()
}

# Adds what $from has and $into lacks. Lists are unioned, hook entries are added when their
# command is new, and a value already in $into is never overwritten, so permission rules
# Claude Code has saved to settings.local.json survive a re-run.
function Merge-Settings($into, $from) {
    foreach ($property in $from.PSObject.Properties) {
        $name = $property.Name
        if ($name -eq 'permissions' -or $name -eq 'hooks') {
            if (-not $into.PSObject.Properties[$name]) {
                Set-Property $into $name (New-Object PSObject)
            }
            $section = $into.$name
            foreach ($child in $property.Value.PSObject.Properties) {
                if ($name -eq 'hooks') {
                    Add-HookEntries $section $child.Name $child.Value
                }
                elseif ($child.Value -is [array]) {
                    Add-ListItems $section $child.Name $child.Value
                }
                elseif (-not $section.PSObject.Properties[$child.Name]) {
                    Set-Property $section $child.Name $child.Value
                }
            }
        }
        elseif ($property.Value -is [array]) {
            Add-ListItems $into $name $property.Value
        }
        elseif (-not $into.PSObject.Properties[$name]) {
            Set-Property $into $name $property.Value
        }
    }
}

# The KFS hooks are referenced in place rather than linked into the clone, so point
# ${CLAUDE_PROJECT_DIR}/.claude/hooks/ commands at the hooks folder itself.
function Update-HookPaths($settings, $hooksPath) {
    if (-not $settings.PSObject.Properties['hooks']) { return }
    foreach ($hookEvent in $settings.hooks.PSObject.Properties) {
        foreach ($entry in @($hookEvent.Value)) {
            foreach ($hook in @($entry.hooks)) {
                if ($hook -and $hook.command) {
                    $hook.command = $hook.command -replace '\$\{CLAUDE_PROJECT_DIR\}/\.claude/hooks/(\S+)', ('"' + $hooksPath + '/$1"')
                }
            }
        }
    }
}

# --- Validate every source up front -----------------------------------------

Write-Host ''
Write-Host 'Validating sources' -ForegroundColor Cyan

Confirm-Source $Target                                  'Target Rock clone'
Confirm-Source (Join-Path $Target 'Rock.Version')       'Target does not look like a Rock clone (no Rock.Version)'
Confirm-Source $Rock20                                  'Rock20 guardrail source clone'
Confirm-Source (Join-Path $Rock20 '.claude\rules')      "Rock20 guardrails (.claude\rules)"
Confirm-Source (Join-Path $Rock20 '.claude\skills')     "Rock20 skills (.claude\skills)"
Confirm-Source (Join-Path $Rock20 'CLAUDE.md')          'Rock20 CLAUDE.md'
Confirm-Source $Guardrails                              'KFS guardrails folder'
Confirm-Source (Join-Path $Guardrails 'rules')          'KFS rules'
Confirm-Source (Join-Path $Guardrails 'hooks')          'KFS hooks'
Confirm-Source (Join-Path $Guardrails 'settings.json')  'KFS settings.json'
Confirm-Source (Join-Path $Guardrails 'CLAUDE-kfs.md')  'KFS CLAUDE-kfs.md'

$Target     = (Resolve-Path -LiteralPath $Target).ProviderPath.TrimEnd('\')
$Rock20     = (Resolve-Path -LiteralPath $Rock20).ProviderPath.TrimEnd('\')
$Guardrails = (Resolve-Path -LiteralPath $Guardrails).ProviderPath.TrimEnd('\')

# v17 and v18 stamp the version in AssemblySharedInfo.cs; v19+ moved it to Directory.Build.props.
$targetVersion = 'unknown'
$stamps = @(
    @{ File = 'Rock.Version\AssemblySharedInfo.cs'; Pattern = 'AssemblyInformationalVersion\(\s*"([^"]+)"' },
    @{ File = 'Directory.Build.props';              Pattern = '<InformationalVersion>([^<]+)<' }
)
foreach ($stamp in $stamps) {
    $stampPath = Join-Path $Target $stamp.File
    if ($targetVersion -eq 'unknown' -and (Test-Path -LiteralPath $stampPath)) {
        $m = Select-String -LiteralPath $stampPath -Pattern $stamp.Pattern | Select-Object -First 1
        if ($m) { $targetVersion = $m.Matches[0].Groups[1].Value }
    }
}

$isRockSource  = $Target -eq $Rock20
$shipsClaudeMd = Test-Tracked 'CLAUDE.md'
$shipsRules    = Test-Tracked '.claude/rules'

if ($shipsRules -and -not $isRockSource) {
    Fail ("$Target ships its own .claude\rules but is not the Rock guardrail source ($Rock20). " +
          "Loading both would give Claude two versions of Rock's rules. Pass -Rock20 $Target to " +
          'make this clone the source, or raise it.')
}

if ($isRockSource) {
    $mode = 'Rock guardrail source - adding the KFS layer only'
}
elseif ($shipsClaudeMd) {
    $mode = "adding Rock20's guardrails and the KFS layer; skipping the clone's own CLAUDE.md"
}
else {
    $mode = "adding Rock20's guardrails and the KFS layer"
}

Write-Host "  ok    target      $Target  ($targetVersion)"
Write-Host "  ok    rock20      $Rock20"
Write-Host "  ok    guardrails  $Guardrails"
Write-Host "  ok    mode        $mode"

# Surface the guardrail source's checkout so stale content is visible.
$checkout = Get-GuardrailsCheckout
if ($checkout) { Write-Host "  ok    guardrails on $checkout" }

# --- Check the clone before changing anything --------------------------------

$claude             = Join-Path $Target '.claude'
$claudeMdPath       = Join-Path $Target 'CLAUDE.md'
$localMdPath        = Join-Path $Target 'CLAUDE.local.md'
$localSettingsPath  = Join-Path $claude 'settings.local.json'
$legacySettingsPath = Join-Path $claude 'settings.json'

$links = [ordered]@{ 'rules\kfs' = (Join-Path $Guardrails 'rules') }
if (-not $isRockSource) {
    $links['rules\rock'] = Join-Path $Rock20 '.claude\rules'
}

# Everything this script writes. None of it may be tracked by the clone.
$owned = @('CLAUDE.local.md', '.claude/settings.local.json')
foreach ($name in $links.Keys) { $owned += '.claude/' + ($name -replace '\\', '/') }
foreach ($path in $owned) {
    if (Test-Tracked $path) {
        Fail "The clone tracks $path. setup.ps1 never writes over a tracked file."
    }
}

# Layouts left by earlier versions of this script. The first linked .claude itself as a junction
# and CLAUDE.md as a hard link into KFSRockAssemblies. The second generated CLAUDE.md, copied
# settings.json into .claude and linked commands and hooks there.
$legacyClaudeJunction = Test-Junction $claude
$legacyJunctions = @()
if (-not $legacyClaudeJunction) {
    foreach ($name in 'commands', 'hooks') {
        $path = Join-Path $claude $name
        if ((Test-Junction $path) -and (((Get-Item -LiteralPath $path -Force).Target -join '') -match '\\\.?guardrails\\')) {
            $legacyJunctions += $path
        }
    }
}
$isLegacySetup = $legacyClaudeJunction -or ($legacyJunctions.Count -gt 0)

$removeClaudeMd = $false
if ((Test-Path -LiteralPath $claudeMdPath) -and -not $shipsClaudeMd) {
    $isGenerated = Select-String -LiteralPath $claudeMdPath -Pattern $GeneratedPattern -Quiet
    $isHardLink  = (Get-Item -LiteralPath $claudeMdPath -Force).LinkType -eq 'HardLink'
    if (-not ($isGenerated -or $isHardLink)) {
        Fail 'CLAUDE.md is neither tracked by the clone nor generated by setup.ps1. Move it aside and re-run.'
    }
    $removeClaudeMd = $true
}

if ((Test-Path -LiteralPath $localMdPath) -and -not (Select-String -LiteralPath $localMdPath -Pattern $GeneratedPattern -Quiet)) {
    Fail 'CLAUDE.local.md exists and was not generated by setup.ps1, which writes its imports there. Move your notes aside and re-run.'
}

$localSettings  = New-Object PSObject
$legacySettings = $null
if (-not $legacyClaudeJunction) {
    if (Test-Path -LiteralPath $localSettingsPath) {
        $localSettings = Read-Json $localSettingsPath
    }

    # An untracked settings.json is the copy an earlier setup made. It is merged, not discarded.
    if ((Test-Path -LiteralPath $legacySettingsPath) -and -not (Test-Tracked '.claude/settings.json')) {
        $isOurCopy = $isLegacySetup -or (Select-String -LiteralPath $legacySettingsPath -Pattern '.claude/hooks/prevent-destructive.sh' -SimpleMatch -Quiet)
        if (-not $isOurCopy) {
            Fail '.claude\settings.json is neither tracked by the clone nor left by an earlier setup.ps1. Move what you need into .claude\settings.local.json, delete it and re-run.'
        }
        $legacySettings = Read-Json $legacySettingsPath
    }

    foreach ($name in $links.Keys) {
        $path = Join-Path $claude $name
        if ((Test-Path -LiteralPath $path) -and -not (Test-Junction $path)) {
            Fail ".claude\$name is a real folder, not a junction. Move it aside and re-run."
        }
    }
}
$kfsSettings = Read-Json (Join-Path $Guardrails 'settings.json')

$skillLinks = [ordered]@{}
$rockSkillCount = 0
$kfsSkillCount = 0
if (-not $SkipSkills) {
    $userSkills = Join-Path $HOME '.claude\skills'
    $rockSkills = @(Get-ChildItem -Directory (Join-Path $Rock20 '.claude\skills'))
    $kfsSkills  = @()
    if (Test-Path -LiteralPath (Join-Path $Guardrails 'skills')) {
        $kfsSkills = @(Get-ChildItem -Directory (Join-Path $Guardrails 'skills'))
    }
    $rockSkillCount = $rockSkills.Count
    $kfsSkillCount  = $kfsSkills.Count
    foreach ($source in ($rockSkills + $kfsSkills)) {
        $link = Join-Path $userSkills $source.Name
        if ((Test-Path -LiteralPath $link) -and -not (Test-Junction $link)) {
            Fail "$link is a real folder, not a junction. Move it aside and re-run, or pass -SkipSkills."
        }
        $skillLinks[$link] = $source.FullName
    }
}

# --- Update the clone -------------------------------------------------------

Write-Host ''
Write-Host "Updating $Target" -ForegroundColor Cyan

if ($legacyClaudeJunction) {
    Remove-Junction $claude
    Write-Host '  note  removed legacy .claude junction'
}
foreach ($path in $legacyJunctions) {
    Remove-Junction $path
    Write-Host "  note  removed legacy $(Split-Path $path -Leaf) junction"
}
if ($removeClaudeMd) {
    Remove-Item -LiteralPath $claudeMdPath -Force
    Write-Host '  note  removed generated CLAUDE.md (replaced by CLAUDE.local.md)'
}

New-Item -ItemType Directory -Path (Join-Path $claude 'rules') -Force | Out-Null
foreach ($name in $links.Keys) {
    Set-Junction (Join-Path $claude $name) $links[$name]
}

$hooksPath = (Join-Path $Guardrails 'hooks') -replace '\\', '/'
Update-HookPaths $kfsSettings $hooksPath
Merge-Settings $localSettings $kfsSettings
if ($null -ne $legacySettings) {
    Update-HookPaths $legacySettings $hooksPath
    Merge-Settings $localSettings $legacySettings
}
if ($shipsClaudeMd -and -not $isRockSource) {
    $skipOwnClaudeMd = New-Object PSObject
    Set-Property $skipOwnClaudeMd 'claudeMdExcludes' @("**/$(Split-Path $Target -Leaf)/CLAUDE.md")
    Merge-Settings $localSettings $skipOwnClaudeMd
}
Write-Utf8 $localSettingsPath (ConvertTo-Json -InputObject $localSettings -Depth 20)
Write-Host '  merge settings.local.json'
if ($null -ne $legacySettings) {
    Remove-Item -LiteralPath $legacySettingsPath -Force
    Write-Host '  note  merged legacy settings.json into settings.local.json and removed it'
}

$kfsClaude = (Join-Path $Guardrails 'CLAUDE-kfs.md') -replace '\\', '/'
if ($isRockSource) {
    $localMd = @"
$GeneratedHeader
<!-- Sources: this clone's own CLAUDE.md and .claude\rules (Rock v20, unmodified) + $Guardrails (KFS delta) -->

Rock's guidelines load first, from this clone's own ``CLAUDE.md``, and are the standard. KFS
departures follow and override them; every conflict is named explicitly in
``.claude/rules/kfs/kfs-precedence.md``.

@$kfsClaude
"@
}
else {
    $rockClaude = (Join-Path $Rock20 'CLAUDE.md') -replace '\\', '/'
    $ownClaudeMdNote = ''
    if ($shipsClaudeMd) {
        $ownClaudeMdNote = "`n<!-- This clone's own CLAUDE.md is an early copy of Rock's. claudeMdExcludes in .claude\settings.local.json skips it. -->"
    }
    $localMd = @"
$GeneratedHeader
<!-- Sources: $Rock20 (Rock v20, unmodified) + $Guardrails (KFS delta) -->$ownClaudeMdNote

Rock's guidelines are imported first and are the standard. KFS departures follow and override
them; every conflict is named explicitly in ``.claude/rules/kfs/kfs-precedence.md``.

@$rockClaude

@$kfsClaude
"@
}
Write-Utf8 $localMdPath $localMd
Write-Host '  gen   CLAUDE.local.md'

Add-GitExclude '/CLAUDE.local.md'
Add-GitExclude '/.claude/settings.local.json'
foreach ($name in $links.Keys) {
    Add-GitExclude ('/.claude/' + ($name -replace '\\', '/'))
}

# --- Machine-wide skills ----------------------------------------------------

if (-not $SkipSkills) {
    Write-Host ''
    Write-Host 'Wiring skills into ~\.claude\skills' -ForegroundColor Cyan

    New-Item -ItemType Directory -Path $userSkills -Force | Out-Null
    foreach ($link in $skillLinks.Keys) {
        Set-Junction $link $skillLinks[$link]
    }
    Write-Host "  $rockSkillCount Rock skills, $kfsSkillCount KFS skills"
}

# --- Done -------------------------------------------------------------------

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green
Write-Host "  Start Claude Code from $Target"
Write-Host '  First time in this clone: approve its external imports by running the claude CLI once'
Write-Host '  from the clone root. The desktop app never shows that prompt.'
Write-Host '  To verify, ask a fresh session, without tools, whether its context contains'
Write-Host "  `"Rock RMS is an open-source church management system`" and `"Rock's conventions are the standard`"."
Write-Host ''
